# Generated by Django 4.0.4 on 2022-04-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Action',
            },
        ),
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('staff', models.CharField(help_text='authenticated user who made this record', max_length=40)),
                ('rid', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, help_text='email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='phone number', max_length=40)),
                ('last', models.CharField(blank=True, help_text='last name', max_length=40)),
                ('first_etc', models.TextField(blank=True, help_text='first name etc.')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.action')),
            ],
            options={
                'verbose_name': 'Photographer',
                'verbose_name_plural': 'Photographer',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('photographer', models.CharField(help_text='authenticated photographer who made this record', max_length=40)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.action')),
                ('refugee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.refugee')),
            ],
            options={
                'verbose_name': 'PhotoTaken',
                'verbose_name_plural': 'PhotoTaken',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('staff', models.CharField(help_text='authenticated user who made this record', max_length=40)),
                ('shop_name', models.CharField(help_text='shop name', max_length=40)),
                ('shop_street', models.CharField(help_text='shop street', max_length=40)),
                ('shop_city', models.CharField(help_text='shop city', max_length=40)),
                ('shop_country', models.CharField(help_text='shop name', max_length=40)),
                ('contact_email', models.EmailField(blank=True, help_text='contact email', max_length=254)),
                ('contact_phone', models.CharField(help_text='phone number', max_length=40)),
                ('conact_name', models.CharField(help_text='contact name', max_length=40)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.action')),
            ],
            options={
                'verbose_name': 'Photographer',
                'verbose_name_plural': 'Photographer',
                'ordering': ['date'],
            },
        ),
    ]
