# Generated by Django 3.2.13 on 2022-04-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_refugee_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='staff',
            new_name='organizer',
        ),
        migrations.RenameField(
            model_name='refugee',
            old_name='staff',
            new_name='organizer',
        ),
    ]
