# Generated by Django 3.2.13 on 2022-04-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_auto_20220426_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='conact_name',
            new_name='contact_name',
        ),
    ]
