# Generated by Django 3.2.12 on 2022-04-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_accounting', 'initial_table_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refugee',
            old_name='first',
            new_name='first_etc',
        ),
        migrations.RemoveField(
            model_name='refugee',
            name='second',
        ),
        migrations.AddField(
            model_name='photographer',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo_accounting.editcommand'),
        ),
        migrations.AddField(
            model_name='refugee',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo_accounting.editcommand'),
        ),
    ]
