# Generated by Django 3.2.12 on 2022-04-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='editCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='refugee',
            name='first',
            field=models.TextField(blank=True, help_text='prénom'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='last',
            field=models.TextField(blank=True, help_text='nom'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='second',
            field=models.TextField(blank=True, help_text='optional autre nom'),
        ),
        migrations.AddField(
            model_name='phototaken',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo_accounting.editcommand'),
        ),
    ]
