"""
Django settings for initial project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# print("BASE_DIR: ", BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-m8y(y83b&+vr9dmasp0d(*pm6zk$m-oz@bb&(k-7g1d8x!0g@w'
SECRET_KEY = 'jp+2x_d9f^2g@kbqq1s34h4+b3@#mf5)#=#hh!q-c8_-gwt!i_' 

# SECURITY WARNING: set DEBUG to False for the production site!
DEBUG = True


ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
  'django.contrib.admin'
  ,'django.contrib.auth'
  ,'django.contrib.contenttypes'
  ,'django.contrib.sessions'
  ,'django.contrib.messages'
  ,'django.contrib.staticfiles'
  ,'photographer.apps.PhotographerConfig'
  ,'organizer.apps.OrganizerConfig'
  ,'shared.apps.SharedConfig'
  ,'qr_code'
]
#GOOGLE_API_KEY = 'AIzaSyD--your-google-maps-key-SjQBE'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'initial.urls'


# don't know why I had to add shared/templates here because shared is an app, so it should be looking there already
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates'
        ,'DIRS': [
          os.path.join(BASE_DIR ,'initial/templates') 
          ,os.path.join(BASE_DIR ,'shared/templates')
        ]
        ,'APP_DIRS': True
        ,'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        }
    }
]

WSGI_APPLICATION = 'initial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3'
        ,'NAME': BASE_DIR / 'db.sqlite3'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    }
    ,{
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    }
    ,{
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    }
    ,{
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

DATE_FORMAT = "Y-m-d"

USE_I18N = True

DATETIME_FORMAT = "Y-m-d\Ti:s\Z"
USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'initial/static')
    ,os.path.join(BASE_DIR, 'organizer/static')
    ,os.path.join(BASE_DIR, 'photographer/static')
    ,os.path.join(BASE_DIR, 'shared/static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587
EMAIL_HOST = 'smtp-relay.gmail.com'
DEFAULT_FROM_EMAIL = 'no-reply@UARPA.org'
